### PR TITLE
Remove WarningInterceptor

### PR DESCRIPTION
**Pull request by gforcada**
See https://github.com/plone/Products.CMFPlone/pull/2046

### CODE REVIEW

**Comment by gforcada** [comment]
@jensens you might want to also want to fix https://github.com/plone/Products.PlonePAS/issues/22 and then merge all of them together?

**Comment by gforcada** [comment]
#120 seems to be the way.

**Comment by jensens** [comment]
Closing and deleting branch was a bit fast, right? The changes are needed anyway.

**Comment by jensens** [comment]
ah, sorry, I was confused

**Pull request closed without merging**
