### PR TITLE
Code quality cleanup

### PR DESCRIPTION
**Pull request by mauritsvanrees**
Based on http://jenkinsploneorg.readthedocs.io/en/latest/run-qa-on-package.html

With this PR we are down from 418 QA failures to 9. What is left is only some too complex code, which seems better to handle separately:

```
$ bin/code-analysis
Check clean lines....................[ OK ] in 0.132s
Flake8..........................[ FAILURE ] in 1.715s
plone/app/upgrade/utils.py:266:1: C901 'updateIconsInBrains' is too complex (19)
plone/app/upgrade/v41/alphas.py:30:1: C901 'add_siteadmin_role' is too complex (14)
plone/app/upgrade/v40/alphas.py:179:1: C901 'migrateActionIcons' is too complex (17)
plone/app/upgrade/v40/betas.py:43:1: C901 'updateSafeHTMLConfig' is too complex (11)
plone/app/upgrade/v40/betas.py:220:1: C901 'fix_cataloged_interface_names' is too complex (11)
plone/app/upgrade/v43/alphas.py:17:1: C901 'reindex_sortable_title' is too complex (11)
plone/app/upgrade/v43/alphas.py:137:1: C901 'upgradeSyndication' is too complex (21)
plone/app/upgrade/v43/final.py:238:1: C901 'removeFakeKupu' is too complex (15)
plone/app/upgrade/v50/betas.py:495:1: C901 'to50rc3' is too complex (19)
Check MANIFEST.in....................[ OK ] in 2.107s
```

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
BTW, small shell script to add the Python coding magic comment:

```
$ cat ~/bin/add-python-coding-magic-comment.sh 
#!/bin/sh
MAGIC="# -*- coding: utf-8 -*-"
# grep gets confused by the hash.  Or I get confused anyway.
DETECT_MAGIC="-*- coding: utf-8 -*-"
if test $# -eq 0; then
    echo "Call with --all to add magic coding comment to all python files recursively."
    echo "Or call with one or more python filenames."
    exit
fi
FILES=$*
if test $# -eq 1; then
    if test "$1" == "--all"; then
        FILES=$(find . -name '*.py')
    fi
fi
for filename in $FILES; do
    if test $(grep -c -- "$DETECT_MAGIC" $filename) -eq 0; then
        echo "fixing $filename"
        mv $filename tmp
        echo $MAGIC > $filename
        cat tmp >> $filename
        rm tmp
    # else
    #     echo "yes $filename"
    fi
done
```

**Comment by mauritsvanrees** [comment]
BTW, flake8 erroneously complains about S001 module formatter for code like this:

    if i % 10000 == 0:
        ...

See https://github.com/plone/plone.app.upgrade/pull/157/commits/5ad40a2d56c263a26b63a84cff6145d633a77221#diff-8aa1e1f3efaba928cc1f41372c58ed94R250

**Comment by gforcada** [comment]
LGTM but I would remove the qa.cfg and bootstrap.py, do we really want those files for anything? :thinking:

**Comment by mauritsvanrees** [comment]
The `qa.cfg` helps when QA problems creep in again. Someone can then use the given buildout.

Or do we want to encourage developers to download a fresh `qa.cfg` from http://jenkinsploneorg.readthedocs.io/en/latest/run-qa-on-package.html when they start another QA session? That may certainly be a good idea, to avoid having outdated QA configs in various packages.

**Comment by gforcada** [comment]
Yes, that would be my idea, do not keep local cfg if possible.

**Pull request merged**
