### PR TITLE
Update `ITinyMCESchema` with new plugin `autolink`

### PR DESCRIPTION
**Pull request by petschki**
see https://github.com/plone/plone.base/pull/25

### CODE REVIEW

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Review by mauritsvanrees — CHANGES_REQUESTED** [review]
This would reapply all settings, and for example change [`date_format_long`](https://github.com/plone/Products.CMFPlone/blob/6.0.0/Products/CMFPlone/profiles/dependencies/registry.xml#L46-L52).

Please create a new profile here in `plone.app.upgrade` with only the changes needed.

**Review by mauritsvanrees — CHANGES_REQUESTED** [review]
I get an error why I try to apply the upgrade:

```
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 181, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 390, in publish_module
  Module ZPublisher.WSGIPublisher, line 285, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 68, in call_object
  Module Products.GenericSetup.tool, line 1135, in manage_doUpgrades
  Module Products.GenericSetup.upgrade, line 218, in doStep
  Module Products.GenericSetup.tool, line 399, in runAllImportStepsFromProfile
   - __traceback_info__: profile-plone.app.upgrade.v60:to6012
  Module Products.GenericSetup.tool, line 1511, in _runImportStepsFromContext
  Module Products.GenericSetup.tool, line 1323, in _doRunImportStep
   - __traceback_info__: plone.app.registry
  Module plone.app.registry.exportimport.handler, line 80, in importRegistry
   - __traceback_info__: registry.xml
  Module plone.app.registry.exportimport.handler, line 127, in importDocument
  Module plone.app.registry.exportimport.handler, line 401, in importRecords
   - __traceback_info__: records name: plone.base.interfaces.ITinyMCESchema
  Module plone.app.registry.exportimport.handler, line 325, in importRecord
   - __traceback_info__: record name: plone.plugins
  Module plone.registry.record, line 82, in _set_value
  Module zope.schema._bootstrapfields, line 298, in validate
  Module zope.schema._field, line 787, in _validate
zope.schema._bootstrapinterfaces.WrongContainedType: ([ConstraintNotSatisfied('autolink', '')], 'value')
```

Could this be because of a validator that still checks against the previously allowed list of values? Just a guess.

**Comment by petschki** [comment]
This should work now with master branch of `plone.base` you will need the updated vocabulary from the `plugins` list there ...

**Review by mauritsvanrees — APPROVED** [review]

**Pull request merged**
