### PR TITLE
Add missing upgrades from plone.staticresources

### PR DESCRIPTION
**Pull request by pbauer**
https://github.com/plone/Products.CMFPlone/issues/2996

### CODE REVIEW

**Comment by pbauer** [comment]
@jenkins-plone-org please run jobs

**Comment by pbauer** [comment]
@thet did you test it? It does not work. Maybe because the upgrade-steps are registered the way they are (I never use  upgradeDepends).

**Comment by jensens** [comment]
Triggering the dependendy-package upgrade step from plone.app.upgrade looks ok to me. otherwise one would need to upgrade the dependendy-package manual under portal_setup->upgrades

**Comment by pbauer** [comment]
I like the solution to upgrade automatically when `@@plone-upgrade` is used. The problem is that in this case it does not work yet. Me pointing at the registration of the upgrade-step was just a wrong guess. The problem is in fact that https://github.com/plone/Products.CMFPlone/pull/2976 was only merged into master of CMFPlone but not into teh branch 5.2.x. 

I'll fix that.

**Comment by pbauer** [comment]
Fixed in https://github.com/plone/Products.CMFPlone/pull/2998

**Pull request closed without merging**
