### PR TITLE
Mockup update

### PR DESCRIPTION
**Pull request by frapell**
Once https://github.com/plone/Products.CMFPlone/pull/2436 is merged, this one brings in the upgrade needed

### CODE REVIEW

**Comment by petschki** [comment]
hey, since I wanted to help out here https://github.com/plone/Products.CMFPlone/pull/2461 (blocker!) I wanted to rebuild plone-logged-in bundle with buildout.coredev 5.1 but mockup/master needs this upgrade step to compile correctly BUT this only gehts updated for v52/to_alpha1 ... so I'm getting dizzy right what's the correct way to get actual compiled bundles for 5.1 cordev?

/cc @frapell @jensens @thet @esteele @MrTango

**Comment by sunew** [comment]
@frapell @petschki @jensens @thet 

These steps are included in to_514 since https://github.com/plone/plone.app.upgrade/pull/168

Do we also need the same steps for 52/to_alpha1 ? (this PR)

**Comment by jensens** [comment]
Hmm, good question. IMO we need it only in ``to_514``, as long as Plone 5.2 was not released. But I would like to have another opinion. 
Also cc @davisagli @mauritsvanrees

**Comment by thet** [comment]
As long we do not have an 5.2 alpha release AND the upgrade step was already included for 5.1.x we do not need the upgrade step here.

**Pull request closed without merging**
