### PR TITLE
add upgradestep for favicon-viewlet

### PR DESCRIPTION
**Pull request by talarias**

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
Wait a minute. Now I think about it, this should not be needed. A viewlet is automatically shown in its viewlet manager as long as it is registered correctly in a zcml file.
Adding it in GenericSetup `viewlets.xml` is only necessary when you want to put viewlets in a specific order. In this case you simply add it, in no particular order. So this PR should not be needed.
Or am I overlooking something?

**Comment by agitator** [comment]
afaik registry entries for controlpanels are automagically created on site creation time and only then...

I had to create those registry settings manually to make an alpha site work again... 🤷🏻‍♂️

**Comment by mauritsvanrees** [comment]
> afaik registry entries for controlpanels are automagically created on site creation time and only then...
> 
> I had to create those registry settings manually to make an alpha site work again... 🤷🏻‍♂️

You are talking about a different commit I think, done directly on master: 5820ed31351d7365916dd14dc529137de151a980.

The current PR only adds a `viewlets.xml`.

**Comment by agitator** [comment]
@mauritsvanrees you're right ;-)

**Comment by mauritsvanrees** [comment]
I close this as unneeded. Please reopen if I am mistaken.

**Pull request closed without merging**
