### PR TITLE
Add an upgrade step for Products.CMFPlone version 5020

### PR DESCRIPTION
**Pull request by b4oshany**
* Merging this will allow the jqtree-contextmenu library to be available in existing plone site.

See [Products.CMFPlone issue 2091](https://github.com/plone/Products.CMFPlone/issues/2091) for more details.

### CODE REVIEW

**Comment by datakurre** [comment]
LGTM.

AFAIK https://github.com/plone/Products.CMFPlone/pull/2090 will pass tests only after this has been merged.

**Comment by datakurre** [comment]
@gforcada We need help with these pulls. This pull and https://github.com/plone/Products.CMFPlone/pull/2090 are probably interdependent, so we are unable to get green build. How should new upgrade steps for CMFPlone be handled from CI point of view?

**Comment by gforcada** [comment]
As said on the other pull request (just re-stating in case other read) you can put multiple pull requests at once on a single jenkins job.

I started a new 5.1 job for you: http://jenkins.plone.org/job/pull-request-5.1/291/ see the parameters: http://jenkins.plone.org/job/pull-request-5.1/291/parameters/

**Comment by datakurre** [comment]
Delaying this was my mistake. I missed that this pull was only for Plone 5.0, and running this for 5.1 was mistake.

**Comment by datakurre** [comment]
@b4oshany This requires rebasing and Plone 5.1 pull for https://github.com/plone/Products.CMFPlone/pull/2090

**Pull request closed without merging**
