### PR TITLE
Avoid triggering user login migration

### PR DESCRIPTION
**Pull request by davisagli**
This is a bit ugly but avoids unnecessary processing while migrating the use_email_as_login setting from portal_properties to portal_registry. It makes a difference for us in a site with over 100k users.

### CODE REVIEW

**Comment by davisagli** [comment]
The 5.2 build succeeded but failed to update the PR status. Can someone review?

**Comment by gforcada** [comment]
If we suppress it, shouldn't we provide a method to run them as needed? Or the site works as expected anyway without migration (then why is needed to begin with?)

**Comment by davisagli** [comment]
@gforcada the migration updates user logins from an event triggered after the value of `use_email_as_login` changes. In this case the value is not changing, only where the setting is stored.

**Comment by jensens** [comment]
@davisagli indeed ugly, but I'd say it is fine. This is a one time migration code....

I'd say it is ok for merge if tests are passing.

**Comment by davisagli** [comment]
The tests passed and then I pushed a rebased commit with a fix to the changelog only. I'll merge.

**Pull request merged**
