### PR TITLE
Remove (really) old upgrades

### PR DESCRIPTION
**Pull request by gforcada**
Fixes
https://github.com/plone/Products.CMFPlone/issues/1778

I didn't remove the 3.3 folder because I was not sure if it was agreed or not... anyone from @plone/framework-team can comment on that?

The other thing missing is to clean up setup.py to really remove some dependencies.

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
+1
@esteele would you agree?
Also, maybe we can grab each other as @plone/release-team Saturday at the conference?

**Comment by gforcada** [comment]
Final decision is to update the interwebs:

- a branch (1.3.x) was created keeping ALL upgrades up to now
- master (once this is merged) will only have from v40 onwards

For 4.3.x upgrades changes need to go on 1.3.x branch, for 5.x upgrades, add them on master

**Comment by davisagli** [comment]
4.3.x upgrades presumably need to be added to both the 1.3.x branch and the master branch.

**Comment by jensens** [comment]
TODO:
- [ ] create 1.x branch
- [ ] set version to 2.0 b/c of a major change (semver!)
- [ ] merge to master

**Comment by mauritsvanrees** [comment]
Small note: when creating a new maintenance branch, we should protect it on github, so people can't force push to it. I have just now done this for branch 1.x. master is already protected.
Yesterday I did this for all Products.* repositories in the plone organization.

I have seen a few cases the past months that kind of looked like someone had forced pushed. I could have been mistaken there.

**Comment by gforcada** [comment]
@jensens I created a 1.3.x and updated buildout.coredev 4.3 branch with it, now that you created the 1.x branch will you add that one there and thus we can remove the 1.3.x?

**Comment by jensens** [comment]
oh, ok, well. looks like one of it is not needed. I'am undecided which one to remove.

**Comment by mauritsvanrees** [comment]
I would say this is a breaking change,  because on master you can no longer upgrade from Plone 2.5 or 3.  So master should be 2.0. And then 1.x makes most sense to me for the maintenance branch.

**Comment by gforcada** [comment]
master is already at 2.0, and 1.x makes sense, I created 1.3.x because I don't expect major changes in there, but 1.x feels better, I will change that

**Comment by gforcada** [comment]
@jensens the 1.x branch was created in the wrong commit. I made it the same as the 1.3.x and deleted that one (I had to unprotect and protect it again)

**Comment by mauritsvanrees** [comment]
Come to think of it, we should now probably do the following on the 1.x branch:

- [ ] Remove the 50 and 51 folders.

- [ ] Undo my changes for trying to use the new `get_installer` introduced in Plone 5.1, and just use `portal_quickinstaller`. No sense in trying when it will always fail.

- [ ] Update the version number to 1.4 for good measure.

I can do that.
Does that sound alright?

**Comment by gforcada** [comment]
@mauritsvanrees sounds good all three of them :+1:

**Comment by jensens** [comment]
@mauritsvanrees agree, this makes it also easier to maintain

**Pull request merged**
