### PR TITLE
Apply volto.blocks behavior if the site was being used as a Volto site

### LINKED ISSUE #304: Upgrade Plone 5.2.10 to 6.0.0b3 does not keep site root's blocks and blocks_layout
I don't know if this is the right place to discuss this or the place should be plone.volto

We have a Plone 5.2.10 site as a backend for a Volto 16 app.

I have migrated Plone to 6.0.0b3 and I have seen that although the Plone site has been migrated into a Dexterity object, and although the old root having the `blocks` and `blocks_layout` properties so that a Volto page can be configured in the root of the site, the migration step did not take this into account.

IMHO the migration code should have taken into account that the site was been used as a Volto site (the `blocks` and `blocks_layout` properties on the root of the site signal them), and if so enable the `Blocks` layout on the Plone Site and migrated the content of the said properties to the proper behavior-provided fields.

Opinions @pbauer @mauritsvanrees @jensens ?

### PR DESCRIPTION
**Pull request by erral**
Fixes #304 

Please @plone/volto-team can someone else using Plone 5.2 as a backend for Volto test this upgrade step to Plone 6?

### CODE REVIEW

**Comment by erral** [comment]
@jenkins-plone-org please run jobs

**Review by mauritsvanrees — APPROVED** [review]
LGTM, but indeed someone who is more into Volto should try it.

If you were using Volto and have already migrated to Plone 6 a/b/rc1 then this code won't be run. But I guess if someone has this case, then they would have concluded that the site did not work properly, so they would not have upgraded a live site. So should be okay.

**Comment by erral** [comment]
It's ok in my case to move it to another upgrade step, the only thing to take into account is that it has to run **after** the site root has been migrated to Dexterity.

**Review by mauritsvanrees — APPROVED** [review]
I approve Katja's changes.

@jenkins-plone-org please run jobs

**Comment by ksuess** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
I would not move it to rc2 but keep it where it was at first, in the alphas. My reasoning: if someone has current already migrated a Volto site to a1 or rc1 or in between, and either has not noticed that the root blocks are missing or does not mind, then we should not suddenly restore the old blocks in rc2. And for people currently still on Plone 5.2, it does not matter when the code gets executed.

**Comment by ksuess** [comment]
> I would not move it to rc2 but keep it where it was at first, in the alphas. My reasoning: if someone has current already migrated a Volto site to a1 or rc1 or in between, and either has not noticed that the root blocks are missing or does not mind, then we should not suddenly restore the old blocks in rc2. And for people currently still on Plone 5.2, it does not matter when the code gets executed.

Yes, you are right.
Block migration only for those who are migrating from Plone 5, so upgrade step in upgrade steps group destination="6000"

As "migration of blocks" is about changing to Dexterity FTI for root, I think this belongs to step handler "change_plone_site_fti" 
- If root is already Dexterity FTI , then the switch to blocks behavior is probably done.
- If not Dexterity FTI, then make root Dexterity FTI and then
  Check if root has properties "blocks" and "blocks_layout":
  Do migration of blocks.

**Comment by erral** [comment]
@jenkins-plone-org please run jobs

**Pull request merged**
