### PR TITLE
Remove portal_css and portal_js

### PR DESCRIPTION
**Pull request by pbauer**
replace https://github.com/plone/plone.app.upgrade/pull/28

### CODE REVIEW

**Comment by jensens** [comment]
@pbauer @gforcada Am I right supposing this is meant for 5.2?

**Comment by pbauer** [comment]
In https://github.com/plone/plone.app.upgrade/pull/28#issuecomment-142701160 @bloodbare said the frameworkteam postponed this to 5.1 and I saw it was not done yet.

**Comment by jensens** [comment]
K, I should know this... Will follow up on this.

**Comment by thet** [comment]
+1 for removing this, but for 5.1 this is too late.

**Let's postpone it to 5.2.**

Also, there is some more work involved:
- plone.app.event's JS/CSS registration has to be changed to use the new resource registry (IIRC this is the only place in core, where resources are registered old-style).
- portal_css and portal_javascript related code paths should be deprecated/removed.

**Comment by jensens** [comment]
The new step need to be moved to the 5.2 upgrade section.

**Comment by sunew** [comment]
@jensens @thet @pbauer moved to 5.2

**Comment by gforcada** [comment]
This is no longer needed, right? @ksuess already fixed it. Re-open if I'm wrong :smile:

**Pull request closed without merging**
