### PR TITLE
Upgrade step for:

### PR DESCRIPTION
**Pull request by Gagaro**
https://github.com/plone/Products.CMFPlone/pull/1115
https://github.com/plone/Products.CMFPlone/pull/1106

### CODE REVIEW

**Comment by jcbrand** [comment]
This pull request is not complete and @vangheem already added the necessary upgrades.
Closing.

**Comment by Gagaro** [comment]
What do you mean by "it's not complete"?

Also, the following part is missing from master:

```
<records interface="Products.CMFPlone.interfaces.ITinyMCESchema" prefix="plone" />
```

**Comment by jcbrand** [comment]
@Gagaro: There were other changes needed in registry.xml that weren't in this pull request.

See here: https://github.com/plone/plone.app.upgrade/commit/7f66d4c065de062ac757158a8817bbc5add6010f

What is the ITinyMCESchema record used for?

**Comment by Gagaro** [comment]
It's for https://github.com/plone/Products.CMFPlone/pull/1115

**Comment by jcbrand** [comment]
Can you please make a new pull request for that? Sorry about the extra effort.

**Comment by Gagaro** [comment]
No problem.

It's there: #57

**Pull request closed without merging**
