### PR TITLE
Alternative solution to the dependency issue WARNING below

### PR DESCRIPTION
**Pull request by do3cc**
this is an alternative solution to the problem that the code needlessly depends on CMFPlacefulWorkflow
This PR reverts the other PR by @maartenkling 
Both solve the problem that plone.app.upgrade is pretty broken right now, but this PR will not add a dependency on CMFPlacefulWorkflow

### CODE REVIEW

**Comment by jensens** [comment]
testing

- [ ] on 4.3 http://jenkins.plone.org/job/pull-request-4.3/48/
- [ ] on 5.0 http://jenkins.plone.org/job/pull-request-5.0/41/

**Comment by jensens** [comment]
failed on 5.0 - but iirc there was a general problem, may you rebase and we try again?

**Comment by jensens** [comment]
@do3cc is this one still valid?

**Comment by do3cc** [comment]
Yes, it would allow us to remove the depency on CMFPlacefulworkflow here

**Comment by jensens** [comment]
again for 5.0 http://jenkins.plone.org/job/pull-request-5.0/425/

**Comment by do3cc** [comment]
you are too fast, I am going to rebase, but my coredev update takes soo long

**Comment by jensens** [comment]
sorry for wasting jenkins cpu cycles :D

**Comment by do3cc** [comment]
5.0 https://github.com/plone/plone.app.upgrade/pull/34

**Comment by do3cc** [comment]
4.3 http://jenkins.plone.org/job/pull-request-4.3/113/

**Comment by do3cc** [comment]
All green!1

**Pull request merged**
