### PR TITLE
fix: getIcon for archetypes

### PR DESCRIPTION
**Pull request by Gagaro**
For https://github.com/plone/Products.CMFPlone/pull/1271

:warning:  We should talk about https://github.com/plone/plone.app.upgrade/issues/60 before merging! :warning:

### CODE REVIEW

**Comment by jensens** [comment]
1. changelog is missing (w/o no merge, so please dont forget to add it)
2. I have no idea if we can update metadata with lesser costs.

**Comment by Gagaro** [comment]
Changelog added.

I am currently working on a catalog with ~25,000 objects in it. Reindexing them one by one would take several hours.

If there is no other choice, maybe this step should be separated to allow the to501 to be easily done, and to allow the reindexing to be done at a later time (or to do it by hand chunk by chunk).

**Comment by jensens** [comment]
i changed the implementation to only deal with metadata. 
May you try with your 25k items if this helps?

**Comment by jensens** [comment]
http://jenkins.plone.org/job/pull-request-5.0/609/

**Comment by Gagaro** [comment]
It helps a lot, it now lasts only 20 minutes.

**Pull request merged**
