### PR TITLE
Ported to plone.app.testing

### PR DESCRIPTION
**Pull request by tomgross**
removed all tests for migrations older than 4.3 -> 5.0

### CODE REVIEW

**Comment by davisagli** [comment]
Please make a branch before this merge, and edit Plone 4.3's sources.cfg to use that branch. Then increment the major version of this branch. And send @esteele something nice since it now takes a lot more care to make sure that this branch always references an up to date profile version from the 4.3 series.

**Comment by tisto** [comment]
@tomgross It seems like your pull request leads to two regressions in plone.app.widgets:

http://jenkins.plone.org/job/plone-5.0-python-2.7/3923/testReport/

I reverted the merge for now to get a green build again:

http://jenkins.plone.org/job/plone-5.0-python-2.7/3927/console

@davisagli Sorry, I saw your message after I merged the commit. Do we really want to use a different branch for Plone 4.3? Since we only removed the tests for the upgrade we should be able to still use one branch for both. Another option would be to run the old tests conditionally but our intention was to keep a single branch.

**Comment by davisagli** [comment]
I missed that it was only the tests that got removed. However this still means that we can't say we are supporting upgrades from older Plone versions in 4.3, if there are no tests to make sure we don't break it.

**Comment by tisto** [comment]
@davisagli I was always under the assumption that we are testing just the upgrade steps (more or less isolated) and that since the code for existing upgrade steps will never change, it is highly unlikely that those tests would ever break. Could be that this assumption was wrong. I did not had a close look at those old tests to be honest. Can you give me an example of an upgrade step tests that would break because of a change that does not happen in the upgrade step itself.

**Comment by davisagli** [comment]
Well, we have both isolated tests for (some) upgrade steps, and an end-to-end test that imports an old ZEXP and makes sure the upgrade steps run (but doesn't make assertions about the result other than that it reached the latest version).

I wouldn't say it's true that upgrade steps never change. For example, there are upgrade steps that do things with the KSS or kupu tools. Once we made those optional, we had to update the upgrade steps so they don't break if those tools are not present. Another example is that once we got rid of the action icons tool, we had to add a dummy implementation of the same class so that old upgrade steps can still read the stored values to move them to the actions tool.

**Comment by tomgross** [comment]
I'm in favor of improving the transmogrifier story for migrations between major versions and use p.a.upgrade only for migrations between minor tasks. This would make maintenance of **all** code make easier not only tests. This would mean we need to document the migration path but is an opportunity to to write additional chapters (migrate from earlier Plone, SharePoint, WordPress, Joomla, Drupal, ...)
Usually the migration between major versions of Plone does not work smoothly or at all in more complex scenarios (ask @zopyx ;-) ) and will take a long time for migration from 2.x to 5.x (AT -> Blob -> DX).

**Comment by gforcada** [comment]
@tomgross :+1:

**Comment by tisto** [comment]
@davisagli Did you see @jensens commit that executes the plone.app.upgrade tests conditionally? 

https://github.com/plone/plone.app.upgrade/commit/e33e06cc73b14fe73ac60ff83616ee7a4ff8d9e3

What's your opinion on that?

**Comment by davisagli** [comment]
I think that approach is good, but it looks like that stops testing upgrades from Plone 3.3 to 4.0 (on the way to 4.3) which the policy says we should still support.

**Pull request merged**
