### PR TITLE
Add upgrade step that removes AtD settings

### PR DESCRIPTION
**Pull request by reinhardt**
See https://github.com/plone/Products.CMFPlone/pull/3765

Is this the right place to add the upgrade? Should I create a new version?

Should I add a towncrier entry?

### CODE REVIEW

**Comment by reinhardt** [comment]
@jenkins-plone-org please run jobs

**Review by mauritsvanrees — APPROVED** [review]

**Comment by mauritsvanrees** [comment]
Missing a changelog entry.  Jenkins is currently running, so let's not bother at this moment.  Once it is finished, we can merge all.  And then I can add the changelog entry directly on master.

Remind me if I forget. :-)

**Comment by reinhardt** [comment]
> Missing a changelog entry. Jenkins is currently running, so let's not bother at this moment. Once it is finished, we can merge all. And then I can add the changelog entry directly on master.
> 
> Remind me if I forget. :-)

There's already “Added upgrade to 6103, Plone 6.1.0a4.”: https://github.com/plone/plone.app.upgrade/blob/master/news/6103.internal

Does that count?

**Comment by mauritsvanrees** [comment]
> There's already “Added upgrade to 6103, Plone 6.1.0a4.”: https://github.com/plone/plone.app.upgrade/blob/master/news/6103.internal
> 
> Does that count?

No, I like to be more specific. :-)
I added a snippet in commit d6d277fc29e9e6329fd4d519218ee11941cd3156.

**Pull request merged**
