### PR TITLE
Remove portal tools

### PR DESCRIPTION
**Pull request by gforcada**
Related to https://github.com/plone/Products.CMFPlone/issues/402

/cc @bloodbare

### CODE REVIEW

**Comment by davisagli** [comment]
This is a good start, and can be merged as is. However we also need to:
1. Write an upgrade step to set up the new registry configuration based on the old registries.
2. Add dummy classes in a fake module so that that step can run even if Products.ResourceRegistries isn't included as a dependency.

**Comment by bloodbare** [comment]
We also need to migrate:

plone.app.caching and Products.CMFPlone that both depends on ResourceRegistries for some logic.

**Comment by jensens** [comment]
is this one still valid?

**Comment by bloodbare** [comment]
We posponed this to Plone 5.1

**Comment by jensens** [comment]
Do we want this in 5.1?

**Comment by pbauer** [comment]
Rebaing was a mess so I replaced this with https://github.com/plone/plone.app.upgrade/pull/139

**Pull request closed without merging**
